name: "mitigate github action"
inputs:
  assetid:
    description: 'The id of the asset that it will get synced'
    required: true
    default: ''
  type:
    description: 'From where the sbom will be generated (image, repo)'
    required: false
    default: ''
  registry:
    description: 'Docker registry of the images'
    required: false
    default: ''
  imagename:
    description: 'Name of docker image of the sbom'
    required: false
    default: ''
  client_id:
    description: 'API Key client from mitigate platform'
    required: true
    default: ''
  client_secret:
    description: 'API Key from mitigate platform'
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      shell: bash

    - name: Generate sbom
      run: |
        if [ "${{ inputs.type }}" = "image" ]
        then
          syft registry:${{ inputs.imagename }} -o cyclonedx-json=my_sbom.json
          ls
        elif [ "${{ inputs.type }}" = "repo" ]
        then
          syft "." -o cyclonedx-json=my_sbom.json
        fi 
      shell: bash
    
    - name: Asset sync
      run: |
        req=$(curl -X POST 'https://keycloak.maggioli-research.gr/auth/realms/mitigate-dev/protocol/openid-connect/token' -H 'Content-Type: application/x-www-form-urlencoded' -d "grant_type=client_credentials&client_id=${{ inputs.client_id }}&client_secret=${{ inputs.client_secret }}")
        token=$(echo "$req" | grep -o '"access_token":"[^"]*' | awk -F'"' '{print $4}')
        curl -X 'POST' "https://dev.mitigate.maggioli-research.gr/mitigate-service/api/asset/sync/${{ inputs.assetid }}" -H 'accept: */*' -H "Authorization: Bearer $token" -H 'Content-Type: multipart/form-data' -F 'file=@my_sbom.json;type=application/json'
      shell: bash